services: 
  dev:
      image: mlops-env-dev
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      hostname: dev
      restart: always
      environment:
        DEV_LOCAL_IP: 172.29.1.7
        DEV_LOCAL_HOSTNAME: dev
      ports:
        - "8001:8001"
        - "8000:8000"
      volumes:
        - ./dev/home:/home/developer
        - ../Data:/landing
        - ../repos:/home/repos
      networks:
        sparknet:
          ipv4_address: 172.29.1.7
      command: /bin/bash
volumes:
  pg_data:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16